version: "3"

services:
  bitcoind:
    image: ruimarinho/bitcoin-core:23.0
    container_name: bitcoincore
    command:
      -regtest=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcpassword=bar
      -rpcport=18443
      -rpcuser=foo
      -server
    ports:
      - 18443:18443
    volumes:
      - ./cln/btc1:/home/bitcoin/.bitcoin

  cln1:
    image: sphinx-cln
    # image: sphinxlightning/sphinx-cln-vls:0.1.2
    container_name: cln1
    command:
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcport=18443
      - --bitcoin-rpcuser=foo
      - --bitcoin-rpcpassword=bar
      - --network=regtest
      - --log-level=debug
      - --alias=sphinx-cln1
      - --grpc-port=10019
      - --subdaemon=hsmd:/usr/local/libexec/c-lightning/sphinx-key-broker
      - --accept-htlc-tlv-types=133773310
      # - --rpc-file=/socket
    environment:
      - EXPOSE_TCP=true
      - GREENLIGHT_VERSION=v0.11.0.1-792-g17cc61c
    ports:
      - "0.0.0.0:9735:9735"
      - 10019:10019
      - 1883:1883
      - 8000:8000
    links:
      - bitcoind
    volumes:
      - ./cln/cln1:/root/.lightning

  cln2:
    image: sphinxlightning/sphinx-cln-test:0.1.0
    container_name: cln2
    command:
      - --addr=0.0.0.0:9736
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcport=18443
      - --bitcoin-rpcuser=foo
      - --bitcoin-rpcpassword=bar
      - --network=regtest
      - --log-level=debug
      - --alias=sphinx-cln2
      - --grpc-port=10020
      - --accept-htlc-tlv-types=133773310
    environment:
      - EXPOSE_TCP=true
    ports:
      - "0.0.0.0:9736:9736"
      - 10020:10020
    links:
      - bitcoind
    volumes:
      - ./cln/cln2:/root/.lightning

