version: "3"

services:
  bitcoind:
    image: ruimarinho/bitcoin-core:23.0
    container_name: bitcoincore
    command:
      -regtest=1
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcpassword=bar
      -rpcport=18443
      -rpcuser=foo
      -server
    ports:
      - 18443:18443
    volumes:
      - ./cln/btc1:/home/bitcoin/.bitcoin

  lightningd:
    image: elementsproject/lightningd:v0.11.1
    container_name: lightningd
    command:
      - --bitcoin-rpcconnect=bitcoind
      - --bitcoin-rpcport=18443
      - --bitcoin-rpcuser=foo
      - --bitcoin-rpcpassword=bar
      - --network=regtest
      - --log-level=debug
      - --alias=sphinx-cln1
      - --grpc-port=10019
      # - --subdaemon=hsmd:/broker/sphinx-key-broker
    environment:
      - EXPOSE_TCP=true
      - GREENLIGHT_VERSION=v0.11.0.1
    expose:
      - "9735"
      - "10019"
      - "1883"
    ports:
      - "0.0.0.0:9735:9735"
      - 10019:10019
      - 1883:1883
    links:
      - bitcoind
    volumes:
      - ./cln/cln1:/root/.lightning
      - ./cln/broker:/broker
